const DELAY_AFTER_KEY_PRESS = 500;
const QUERY_DEBOUNCE_DURATION_MILLISECONDS = 500;
const API_URL = 'http://127.0.0.1:3000/api';

export { QUERY_DEBOUNCE_DURATION_MILLISECONDS, DELAY_AFTER_KEY_PRESS, API_URL };
